spring:
  application:
    name: bussinesunit-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
---

spring:
  profiles: docker
  data:
    mongodb:
      host: business-unit-mongo
  rabbitmq:
      host: rabbitmq
app:
  rabbitmq:
      host: rabbitmq